### ISSUE TITLE
Class 'Symplify\Astral\NodeFinder\SimpleNodeFinder' not found

### ISSUE THREAD

**Issue by lulco** [revealphp/reveal#1]
Hi, after update, I got error:
```
Service of type Reveal\RevealLatte\NodeAnalyzer\LatteTemplateWithParametersMatcher: Class 'Symplify\Astral\NodeFinder\SimpleNodeFinder' required by $simpleNodeFinder in LatteTemplateWithParametersMatcher::__construct() not found  
  . Check the parameter type and 'use' statements. 
```

I found that SimpleNodeFinder was removed from Astral package, so what will be the replacement? Or how can i make reveal-latte work again?

**Comment by TomasVotruba** [comment]
Hi, that's because of https://phpstan.org/blog/preprocessing-ast-for-custom-rules

Our architecture must be updated to work without parent/next/previous node.
