### ISSUE TITLE
Packages not working on PHP 7.x

### ISSUE THREAD

**Issue by lulco** [revealphp/reveal#13]
It is declared:
"develop on PHP 8.1 for the best contributor experience
downgrade on release to PHP 7.1, so anyone can use them"

But while we need symplify packages (e.g. astral, phpstan-rules) to run e.g. reveal-latte, we can't use them on PHP < 8

**Comment by TomasVotruba** [comment]
That's because transitional Symplify dependencies are not downgraded.
There are 2 ways:

* add downgrade to Symplify packages
* remove dependency on those

I made the 2nd option happen for phpstan-rules here: https://github.com/revealphp/reveal/blob/main/packages/phpstan-rules/composer.json

**Comment by lulco** [comment]
I don't think 2nd option is doable, there are so many dependencies on symplify packages.
Actually I don't need it because I run reveal-latte on PHP 8.1, I just think you (we) shouldn't declare that reveal packages are running on PHP 7.x

**Comment by TomasVotruba** [comment]
> shouldn't declare that reveal packages are running on PHP 7.x

Agreed :+1:
